services:
  db:
    image: postgres:14.3
    restart: always
    ports:
      - "5436:5436"
    environment:
      POSTGRES_PASSWORD: 'password'
      POSTGRES_DB: 'Practica05'
      POSTGRES_PORT: 5436
    container_name: Practica05
    volumes:
      - ./postgres-data:/var/lib/postgresql/data